#!/bin/bash
gitRelease="https://github.com/MaloriMakes/VS-ChungleMegaPack/releases/latest/download/VS-ChungleMegaPack.zip"
vinMods=$(realpath ~/.var/app/at.vintagestory.VintageStory/config/VintagestoryData/Mods)
chungPack="VS-ChungleMegaPack.zip"
rm -rf "$vinMods/avalirdx-modlink"
rm -rf "$vinMods/chancerdx-modlink"
rm -rf "$vinMods/diriotterrdx-modlink"
rm -rf "$vinMods/foxxoplymdl-modlink"
rm -rf "$vinMods/jadoroordx-modlink"
rm -rf "$vinMods/jorunnyrdx-modlink"
rm -rf "$vinMods/knittyrdx-modlink"
rm -rf "$vinMods/koboldplayerrdx-modlink"
rm -rf "$vinMods/otterrdx-modlink"
rm -rf "$vinMods/rhasaboldrdx-modlink"
rm -rf "$vinMods/tigerrdx-modlink"
curl -L "$gitRelease" -o "$vinMods/$chungPack"
cd "$vinMods"
unzip "$vinMods/$chungPack"
rm "$vinMods/$chungPack"