set "gitRelease=https://github.com/MaloriMakes/VS-ChungleMegaPack/releases/latest/download/VS-ChungleMegaPack.zip"
set "vinMods=%appdata%\VintagestoryData\mods"
set "chungPack=VS-ChungleMegaPack.zip"
cd /D "%vinMods%"
curl -L "%gitRelease%" -o "%vinMods%\%chungPack%"
if exist "%vinMods%\avalirdx-modlink" rmdir /S /Q "%vinMods%\avalirdx-modlink"
if exist "%vinMods%\chancerdx-modlink" rmdir /S /Q "%vinMods%\chancerdx-modlink"
if exist "%vinMods%\diriotterrdx-modlink" rmdir /S /Q "%vinMods%\diriotterrdx-modlink"
if exist "%vinMods%\foxxoplymdl-modlink" rmdir /S /Q "%vinMods%\foxxoplymdl-modlink"
if exist "%vinMods%\jadoroordx-modlink" rmdir /S /Q "%vinMods%\jadoroordx-modlink"
if exist "%vinMods%\jorunnyrdx-modlink" rmdir /S /Q "%vinMods%\jorunnyrdx-modlink"
if exist "%vinMods%\knittyrdx-modlink" rmdir /S /Q "%vinMods%\knittyrdx-modlink"
if exist "%vinMods%\koboldplayerrdx-modlink" rmdir /S /Q "%vinMods%\koboldplayerrdx-modlink"
if exist "%vinMods%\otterrdx-modlink" rmdir /S /Q "%vinMods%\otterrdx-modlink"
if exist "%vinMods%\rhasaboldrdx-modlink" rmdir /S /Q "%vinMods%\rhasaboldrdx-modlink"
if exist "%vinMods%\tigerrdx-modlink" rmdir /S /Q "%vinMods%\tigerrdx-modlink"
if exist "%vinMods%\koboldplayerrdx_1.4.14" rmdir /S /Q "%vinMods%\koboldplayerrdx_1.4.14"
if exist "%vinMods%\foxxoplymdl_1.0.9" rmdir /S /Q "%vinMods%\foxxoplymdl_1.0.9"
tar -xf "%vinMods%\%chungPack%"
del "%vinMods%\%chungPack%"
pause